### ISSUE TITLE
slider not working reliably

### ISSUE THREAD

**Issue by kayiwa** [DocNow/docnow#102]
reported by Bergis and @alexandradm 

Slider on Tweet Archive Viewer.

**Comment by raffazizzi** [comment]
Just checked and noticed it doesn't work properly with collections <200 tweets. Will investigate

**Comment by raffazizzi** [comment]
Completed in https://github.com/DocNow/tweet-archive/commit/f67da5ccd92c91e61d7e18a7c9fb4c0b99877910
