### ISSUE TITLE
Explore using Material Components Web by migrating DocNow App Homepage

### ISSUE THREAD

**Issue by edsu** [DocNow/docnow#106]
The goal here is to explore whether Material Design could help make the DocNow app look and feel a bit more uniform and familiar. while also easing some of the pressure on custom designing components.

**Comment by edsu** [comment]
Raff Viglianti ( https://app.asana.com/0/1116668938924959/list ) created a branch on GitHub for these experiments: https://github.com/DocNow/docnow/tree/material

**Comment by edsu** [comment]
I was reading this https://blog.bitsrc.io/9-web-component-ui-libraries-you-should-know-in-2019-9d4476c3f103 and wondering if we should try the web-components flavor https://github.com/material-components/material-components-web-components although we are using react, and that is unlikely to change.

**Comment by edsu** [comment]
➤ Raff Viglianti commented:

Ed Summers ( https://app.asana.com/0/1116668938924935/list ) I'd love to experiment with that and learn more about Web Components in general. I suggest to focus on the 'Add Place' component on the home page and rewrite it in both MCW-React and MCW-WebComponents and compare

**Comment by edsu** [comment]
I like that idea!

**Comment by raffazizzi** [comment]
We moved to material-ui
