### ISSUE TITLE
JSlint should run on /src/server too

### ISSUE THREAD

**Issue by edsu** [DocNow/docnow#11]
At the moment jslint is running as part of webpack configuration which only processes the src/client code. It would be nice if jslint ran on /src/server code as well. Perhaps the best place to do this is in the `package.json` when running `npm start`. It would be nice if the server failed to start if the linter failed. Also, it could be useful if `npm test` exercised jslint on src.

**Comment by raffazizzi** [comment]
Fixed by https://github.com/DocNow/docnow/commit/1663ec21dbb427cefbcdebdfddd0a5acc5dcb48d
