### ISSUE TITLE
Register for twitter's developer API

### ISSUE THREAD

**Issue by kayiwa** [DocNow/docnow#116]
registration for Twitter's API (this ticket can also live under twarc) has become discouragingly difficult. Some of the questions asked are

- The core use case, intent, or business purpose for your use of the Twitter APIs
- If you intend to analyze Tweets, Twitter users, or their content, share details about the analyses you plan to conduct and the methods or techniques
- If your use involves Tweeting, Retweeting, or liking content, share how you will interact with Twitter users or their content
- If you’ll display Twitter content off of Twitter, explain how and where Tweets and Twitter content will be displayed to users of your product or service, including whether Tweets and Twitter content will be displayed at row level or aggregated

Which by my measure would make me throw my hand up in the air. My primary use case happens to be, make sure folks using our apps can actually use it.

**Comment by edsu** [comment]
What action can we take here?

**Comment by kayiwa** [comment]
I think this was growing pains on Twitter. @alexandradm had a different experience that was faster.
