### ISSUE TITLE
Slow queries on landing page

### ISSUE THREAD

**Issue by kayiwa** [DocNow/docnow#162]
The landing page queries the trend table that seems to take longer as the history grows. What insights can we get using EXPLAIN and/or Google Cloud Platform.

**Comment by edsu** [comment]
It's possible that the slow query problem on demo was partly the result of the amount of requests was getting. I don't think we have tons of users, but some of the views auto-refresh, and could run when someone has a tab open with the app in it...

**Comment by edsu** [comment]
I'm not 100% sure I've solved this in our Google Cloud environment, but I did notice PGHero suggesting we add an index on (created, place_id). Hopefully that will speed up trend lookups. We can reopen this if not.
