### ISSUE TITLE
docnow_app_1 exited(127)

### ISSUE THREAD

**Issue by pvperez1** [DocNow/docnow#163]
Hi, newbie here. I am trying to install docnow on my Windows 10 laptop. On docker, pghero, docnow_redis_1, and docnow_db_1 are all running but docnow_app_1 is not running with status: exited(127). When I clicked on it, I get this message on the command prompt:
/usr/bin/env: 'bash\r': No such file or directory

Any idea how I can fix this? Thank you!

**Comment by edsu** [comment]
I don't know what you clicked on. If you can share a chunk of your docker-compose log prior to the `docnow_app_1  is not running with status: exited(127)` that would be helpful!
