### ISSUE TITLE
Hover on Colors

### ISSUE THREAD

**Issue by kayiwa** [DocNow/docnow#178]
Upon connecting provide the user with context of what the colors mean. If this
is a hashtag, a keyword or a phrase.

**Comment by alexandradm** [comment]
I think the best way to achieve this is to combine the intro element feature explaining the page with a visual key. something like: 
    introElement = (
      <div className={style.Intro}>
        Enter a <span className={style.Hashtag}>hashtag</span>, <span className={style.User}>user</span>, or <span className={style.Phrase}>phrase</span> to explore the most recent 1000 tweets containing that term. You can refine and re-run your search until you have the best terms for your collecting goals before saving.
      </div>

working on it now!
