### ISSUE TITLE
Video URLs

### ISSUE THREAD

**Issue by edsu** [DocNow/docnow#180]
The search display includes a Videos card. With the Twitter v1.1 API this used the mp4 URL of the video which was available in the tweet JSON payload. Unfortunately the v2 API no longer includes the URL of the video :-(

https://twittercommunity.com/t/how-to-get-video-from-media-key/152449

We still can tell which tweets have videos, but we just can't reference the video directly. Maybe there's a way to reverse engineer the video URL? Or maybe we need to remove this component until it becomes available. However, having a broken video display in the DocNow app is not a good look.

<img width="1792" alt="Screen Shot 2022-02-12 at 8 47 42 AM" src="https://user-images.githubusercontent.com/33829/153713945-d3513f52-e14f-4c0d-99ed-56e33ea91817.png">

**Comment by edsu** [comment]
One approach would be to collect the tweets via the v2 API (as we currently do) and then to cherry pick the tweets with video and use the v1.1 API to get the MP4 URL. This is not a very satisfying solution because the v1.1 solution will go away. But maybe by that time the MP4 URL will be available via the V2 API?

**Comment by edsu** [comment]
I'm also looking at how [youtube-dl](https://github.com/ytdl-org/youtube-dl/blob/d1b9a5e2eff1c075b38815a3d2b25eb8b3f626bb/youtube_dl/extractor/twitter.py) downloads videos from tweets. At first glance it appears that it might be using the v1.1 API with a hard coded BEARER_TOKEN?!

**Comment by edsu** [comment]
FWIW it does look like youtube_dl are using the v1.1 API (with a baked in BEARER_TOKEN) to extract the [expanded_url](https://github.com/ytdl-org/youtube-dl/blob/d1b9a5e2eff1c075b38815a3d2b25eb8b3f626bb/youtube_dl/extractor/twitter.py#L570) from the video metadata. So there are no heuristics to borrow there. If we want to follow the same approach we can talk to the API directly using the apps keys like we are [for trends](https://github.com/DocNow/docnow/blob/main/src/server/twitter.js#L80-L92). It might make sense to drop these on a queue to lookup up several tweets at a time rather than one-by-one to avoid rate limiting.

**Comment by alexandradm** [comment]
> 

i like this solution for launch! and can address in full later.

**Comment by edsu** [comment]
Just noting here that if you watch the network traffic in browser devtools when viewing a tweet with a URL you can see that the browser makes a call to `https://twitter.com/i/api/graphql/P3-tzII5Lel_LoJH10ga-Q/TweetDetail` and gets back a chunk of JSON that includes the video URL. Here's a screenshot while using a private browser (not logged into Twitter):

<img width="1328" alt="Screen Shot 2022-02-12 at 1 41 43 PM" src="https://user-images.githubusercontent.com/33829/153724393-c57ca054-18f5-4d4f-ae27-131a5bff96a1.png">

Unfortunately it looks like you need to send a Bearer Token and a Guest Token to be able to talk to this GraphQL endpoint:

```python

import requests

resp = requests.get(
    'https://twitter.com/i/api/graphql/P3-tzII5Lel_LoJH10ga-Q/TweetDetail?variables={"focalTweetId":"1492545746318540810","with_rux_injections":false,"includePromotedContent":true,"withCommunity":true,"withQuickPromoteEligibilityTweetFields":true,"withBirdwatchNotes":false,"withSuperFollowsUserFields":true,"withDownvotePerspective":false,"withReactionsMetadata":false,"withReactionsPerspective":false,"withSuperFollowsTweetFields":true,"withVoice":true,"withV2Timeline":false,"__fs_dont_mention_me_view_api_enabled":false,"__fs_interactive_text_enabled":false,"__fs_responsive_web_uc_gql_enabled":false}',
    headers={
        "authorization": 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA',
        'x-guest-token': '1492570115904352257'
    }
)

print(resp.json())
```

It would be possible to get `authorization` and `x-guest-token` following a similar approach as [snscrape](https://github.com/JustAnotherArchivist/snscrape/blob/master/snscrape/modules/twitter.py#L356-L365) but then we are basically scraping Twitter which we've avoided doing so far in the DocNow app.
