### ISSUE TITLE
Callback URL error

### ISSUE THREAD

**Issue by telezoic** [DocNow/docnow#220]
Hi Folks, 

I've deployed the docnow docker instance and I'm getting an repeated error with my callback URL. Admittedly, the twitter end is this is not a straightforward as I would hope :), but I'm wondering if you had any troubleshooting advice (perhaps you've seen this before . . .or there's a more a verbose log somewhere?) 

In the Twitter end I set my call back URL: 

![Screen Shot 2022-05-09 at 08 50 53](https://user-images.githubusercontent.com/444648/167450708-66ee6c88-41e2-471e-bd22-4886177f3dd5.png)
  

and when I attempt the save in Docnow: 

![Screen Shot 2022-05-09 at 08 51 02](https://user-images.githubusercontent.com/444648/167450817-79aa303a-98cf-4846-8fac-ca5321958cf3.png)

I've regenerated my keys a few times and replaced the app, to no effect. 

Thanks for considering, 

Dan

**Comment by telezoic** [comment]
Thanks @edsu! 

I have a proxypass directive enabled in apache. . . 

```

         ProxyPreserveHost on

        ProxyPass / http://docnow.viulibrary.ca:3000/
        ProxyPassReverse / http://docnow.viulibrary.ca:3000/
        
        
        ```
        
I will disable this and test :)

**Comment by edsu** [comment]
Oh good! So you were able to move forward?

**Comment by telezoic** [comment]
I was. 

Thanks again!
