### ISSUE TITLE
Design Components

### ISSUE THREAD

**Issue by edsu** [DocNow/docnow#24]
We're looking at creating a set of design components similar to [Material Design](https://material.io/) so that we can drop snippets of HTML/CSS into our various apps, but mostly focused on the DocNow app. Since some might get used in other projects we should put these in a new repository, docnow-design?

To get started let's see if we can create some components required on the settings page.

**Comment by alexandradm** [comment]
i made a repo here: https://github.com/alexandradm/docnow-design
not worrying about compiling css files for now
