### ISSUE TITLE
Search View

### ISSUE THREAD

**Issue by edsu** [DocNow/docnow#33]
Now that we have a homepage that lists trending hashtags we can start to implement a Search view that it can link to. The idea is that a logged in user can click on a hashtag on the homepage and go to a page that summarizes the recent history of that hashtag. You can see a sketch of this page in [this design](https://projects.invisionapp.com/share/VPBXQBIK2#/screens/233813826):

![screen shot 2017-08-10 at 2 39 41 pm](https://user-images.githubusercontent.com/33829/29186276-e62c9a94-7dd9-11e7-8ca4-19ef7177f6f6.png)

**Comment by edsu** [comment]
Started work on the [search](https://github.com/DocNow/docnow/tree/search) branch.

**Comment by raffazizzi** [comment]
I've created components for the page with mocked responses from the server. Will circle back to this page after we figure out the server-side piece.

**Comment by edsu** [comment]
The server side piece for this is working now on the [search-api](https://github.com/DocNow/docnow/tree/search-api) branch. I'm going to merge it in and close this issue.
