### ISSUE TITLE
trends_1 error

### ISSUE THREAD

**Issue by alexandradm** [DocNow/docnow#4]
django_1   | [10/Apr/2017 16:20:01] "GET /favicon.ico HTTP/1.1" 404 2690
django_1   | [10/Apr/2017 16:20:06] "GET /api/v1/trends HTTP/1.1" 200 3185
django_1   | [10/Apr/2017 16:20:11] "GET /api/v1/trends HTTP/1.1" 200 3185
django_1   | [10/Apr/2017 16:20:16] "GET /api/v1/trends HTTP/1.1" 200 3185
django_1   | [10/Apr/2017 16:20:21] "GET /api/v1/trends HTTP/1.1" 200 3185
django_1   | [10/Apr/2017 16:20:26] "GET /api/v1/trends HTTP/1.1" 200 3185
django_1   | [10/Apr/2017 16:20:31] "GET /api/v1/trends HTTP/1.1" 200 3185
trends_1   | ERROR:root:list index out of range

happens repeatedly, cycling through build

**Comment by edsu** [comment]
I'm not sure what's happening here but it seems like the app is running but the user table in the database is empty! If you figure out a sequence of actions that cause this to happen please let me know so I can replicate it.

**Comment by edsu** [comment]
The old Python based server app has been replaced with a Node/Express application. So this particular error no longer applies.
