### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by edsu** [DocNow/docnow#43]
We should be running demo.docnow.io under SSL/https.

**Comment by edsu** [comment]
Ideally there would be a ansible playbook for doing this, but maybe it would be easier to do it manually at first. I'll get you account first.

**Comment by edsu** [comment]
So did you end up doing this manually? I see that certbot is setup in root's cron which is good to see!

**Comment by kayiwa** [comment]
yes I did it manually.  Installing what would be needed for certbot can be automated but (as best as I can tell) it requires someone at the wheel to accept even the sensible defaults. It will make for an interesting issue though.
