### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by edsu** [DocNow/docnow#49]
It would be nice to have a fancier "loading" animated gif for the cards as they are populated. Perhaps something related to our logo, or something simple that's better than the word "loading"?

**Comment by alexandradm** [comment]
maybe the twitter bird logo flying across loading dots?

**Comment by alexandradm** [comment]
something like this: https://dribbble.com/shots/1370599--GIF-Progress-Bar-for-Aviasales-app

**Comment by edsu** [comment]
Yeah, that would be cool. Even something simple would work I think.

**Comment by edsu** [comment]
We can revisit this later if needed, but for now I'm closing it due to lack of activity.
