### ISSUE TITLE
Feature request: Omit RT from Tweets box

### ISSUE THREAD

**Issue by justinlittman** [DocNow/docnow#71]
The Tweets box on the Explore page is very helpful for assessing the tweets that match a query. However, depending on the query the Tweets box may be primarily populated with retweets of the same tweet.

It would be useful to be able to (1) optionally omit retweets from the Tweets box or (2) collapse retweets into a single entry.

**Comment by edsu** [comment]
👍 I like that idea, thanks @justinlittman!

**Comment by edsu** [comment]
With the retweets gone I thought it was useful to order the results by the number of times an original tweet was retweeted. You can see this new behavior deployed now demo.docnow.io if you want to check it out. Feedback is welcome, as always!
