### ISSUE TITLE
Homescreen Icon?

### ISSUE THREAD

**Issue by edsu** [DocNow/docnow#93]
Could we get a 320 x 460 PNG version of the DocNow image (DN in Blue) so that (in theory) it can be used as a [home screen icon](https://stuffandnonsense.co.uk/blog/home-screen-icons-and-startup-screens)?

**Comment by alexandradm** [comment]
![dn320x460](https://user-images.githubusercontent.com/425783/38570983-3422df40-3cbd-11e8-9fed-ea167ef702aa.png)
